### PR TITLE
Add the ResNet model

### PR DESCRIPTION
**Pull request by thkim0022**
I worked to add the ResNet model

### CODE REVIEW

**Comment by munhouiani** [comment]
Good work! Do you have any evaluation results?

**Comment by thkim0022** [comment]
I am running to train model and eval
if it finished, I will share the results

**Comment by thkim0022** [comment]
This result is best but less than CNN model
If this model is improved, the result will better than CNN model

[Hyper parameter]
c1_output_dim=16
epoch=40
the other is default 

KakaoTalk_Photo_2022-11-30-21-02-24

**Comment by munhouiani** [comment]
The result is not bad. I'll take time to review and merge.

**Review by munhouiani — APPROVED** [review]

**Comment by munhouiani** [comment]
Thanks!

**Pull request merged**
